app = "mokupona-stack-b568"
kill_signal = "SIGINT"
kill_timeout = 5
processes = [ ]
swap_size_mb = 512

[env]
DATABASE_URL = "file:/data/sqlite.db"
IMAGE_UPLOAD_FOLDER = "/data/uploads/images"
PORT = "8080"

[experimental]
auto_rollback = true

[mounts]
source = "data"
destination = "/data"

[http_service]
internal_port = 8080
force_https = true

  [[http_service.checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/healthcheck"
  timeout = "2s"
